import os
import re
from datetime import datetime, timedelta

VAULT_ROOT = "/Users/dkmac/Desktop/@26/dev"
WIKI_DIR = os.path.join(VAULT_ROOT, "wiki")
PROJECTS_DIR = os.path.join(VAULT_ROOT, "projects")
OPS_DIR = os.path.join(VAULT_ROOT, "_ops")
CHANGELOG_PATH = os.path.join(OPS_DIR, "change-log.md")
DASHBOARD_PATH = os.path.join(VAULT_ROOT, "KNOWLEDGE_PULSE.md")

def get_file_count(directory):
    if not os.path.exists(directory): return 0
    return sum(len([f for f in files if f.endswith(".md")]) for _, _, files in os.walk(directory))

def get_metabolic_pulse():
    if not os.path.exists(CHANGELOG_PATH): return " " * 7
    with open(CHANGELOG_PATH, 'r') as f:
        content = f.read()
    current_date = datetime.now()
    pulse = []
    for i in range(6, -1, -1):
        date_str = (current_date - timedelta(days=i)).strftime("%Y-%m-%d")
        if f"## {date_str}" in content:
            section = content.split(f"## {date_str}")[1].split("##")[0]
            pulse.append("█" if len(re.findall(r'### ', section)) > 1 else "▄")
        else: pulse.append(" ")
    return "".join(pulse)

def get_recent_activity():
    cutoff = datetime.now() - timedelta(days=3)
    recent = []
    for root, _, files in os.walk(VAULT_ROOT):
        if any(x in root for x in [".git", "node_modules"]): continue
        for f in files:
            if f.endswith(".md") and not f.startswith("."):
                path = os.path.join(root, f)
                try:
                    mtime = datetime.fromtimestamp(os.path.getmtime(path))
                    if mtime > cutoff:
                        recent.append((os.path.relpath(path, VAULT_ROOT), mtime))
                except: continue
    return sorted(recent, key=lambda x: x[1], reverse=True)[:5]

def generate():
    l2 = get_file_count(os.path.join(WIKI_DIR, "concepts"))
    l3 = len([d for d in os.listdir(PROJECTS_DIR) if os.path.isdir(os.path.join(PROJECTS_DIR, d))])
    pulse = get_metabolic_pulse()
    recent = get_recent_activity()
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    content = f"""---
type: Dashboard
_icon: brain
_color: "#ff00ff"
last_update: {now}
status: {"🟢 ACTIVE" if "█" in pulse or "▄" in pulse else "⚪️ STEADY"}
---

# 🧠 CSP-Brain 지식 진화 대시보드 (Know-Grow)

> "지능은 저장의 양이 아니라, 연결의 밀도와 변화의 속도로 증명됩니다."

## 1. 지식 대사 활성도 (Pulse)
최근 7일간의 지식 업데이트 밀도입니다.

` {pulse} ` (Current Status)

## 2. 계층별 지능 밀도 (7-Layer Density)
- **L2 Concepts**: {l2} Atoms (개념 원자 자산)
- **L3 Projects**: {l3} Projects (실행 면적)

## 3. 최근의 지능적 도약 (Recent Synapses)
"""
    for path, t in recent:
        content += f"- **[{t.strftime('%m-%d %H:%M')}]** `{path}`\n"
        
    content += "\n---\n*Generated by Know-Grow Monitor Script*"
    with open(DASHBOARD_PATH, "w") as f: f.write(content)

if __name__ == "__main__": generate()
