/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ThinkLogPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/InputView.ts
var import_obsidian = require("obsidian");
var VIEW_TYPE_THINKLOG_INPUT = "thinklog-input-view";
var SECTIONS = [
  {
    id: "observations",
    icon: "eye",
    title: "Observations",
    titleKo: "\uAD00\uCC30",
    prompt: "\uC624\uB298 \uBB34\uC5C7\uC744 \uAD00\uCC30\uD588\uB098\uC694?",
    prompts: ["\uBB34\uC5C7\uC744 \uBCF4\uACE0 \uB4E4\uC5C8\uB098\uC694?", "\uC5B4\uB5A4 \uC0AC\uC2E4\uC744 \uBC1C\uACAC\uD588\uB098\uC694?", "\uC624\uB298\uC758 \uD604\uC0C1\uC740?"],
    placeholder: "\uC0AC\uC2E4 \uAE30\uBC18\uC758 \uAD00\uCC30\uC744 \uC801\uC5B4\uC8FC\uC138\uC694...",
    color: "#3b82f6"
  },
  {
    id: "thoughts",
    icon: "message-circle",
    title: "Thoughts",
    titleKo: "\uC0DD\uAC01",
    prompt: "\uC5B4\uB5A4 \uC0DD\uAC01\uC774 \uB5A0\uC62C\uB790\uB098\uC694?",
    prompts: ["\uC774\uAC83\uC5D0 \uB300\uD574 \uC5B4\uB5BB\uAC8C \uC0DD\uAC01\uD558\uC138\uC694?", "\uC5B4\uB5A4 \uC544\uC774\uB514\uC5B4\uAC00 \uC788\uB098\uC694?", "\uB290\uB080 \uC810\uC740?"],
    placeholder: "\uB5A0\uC624\uB978 \uC544\uC774\uB514\uC5B4\uB098 \uC758\uACAC\uC744 \uC801\uC5B4\uC8FC\uC138\uC694...",
    color: "#8b5cf6"
  },
  {
    id: "questions",
    icon: "help-circle",
    title: "Questions",
    titleKo: "\uC9C8\uBB38",
    prompt: "\uAD81\uAE08\uD55C \uC810\uC740?",
    prompts: ["\uD655\uC778\uC774 \uD544\uC694\uD55C \uAC83\uC740?", "\uC544\uC9C1 \uBAA8\uB974\uB294 \uAC83\uC740?", "\uB354 \uC54C\uC544\uBD10\uC57C \uD560 \uAC83\uC740?"],
    placeholder: "\uAD81\uAE08\uD55C \uC810\uC774\uB098 \uD655\uC778\uC774 \uD544\uC694\uD55C \uAC83...",
    color: "#ec4899"
  }
];
var ThinkLogInputView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.saveTimeout = null;
    this.themes = [];
    this.currentFile = null;
    this.plugin = plugin;
    this.data = this.getEmptyData();
  }
  getViewType() {
    return VIEW_TYPE_THINKLOG_INPUT;
  }
  getDisplayText() {
    return "ThinkLog Input";
  }
  getIcon() {
    return "edit-3";
  }
  getEmptyData() {
    return {
      theme: "",
      observations: [],
      thoughts: [],
      questions: [],
      dataPoints: [],
      actions: [],
      quickCapture: ""
    };
  }
  async onOpen() {
    await this.loadThemes();
    await this.loadTodayLog();
    this.render();
  }
  async onClose() {
    if (this.saveTimeout) {
      clearTimeout(this.saveTimeout);
      await this.save();
    }
  }
  async loadThemes() {
    const files = this.app.vault.getMarkdownFiles();
    const themeSet = /* @__PURE__ */ new Set();
    for (const file of files) {
      if (file.path.includes(this.plugin.settings.dailyNotesFolder)) {
        const content = await this.app.vault.cachedRead(file);
        const theme = this.extractTheme(content);
        if (theme)
          themeSet.add(theme);
      }
    }
    this.themes = Array.from(themeSet).sort();
  }
  extractTheme(content) {
    const fmMatch = content.match(/^---\n[\s\S]*?theme:\s*(.+?)\n[\s\S]*?---/m);
    if (fmMatch && fmMatch[1].trim())
      return fmMatch[1].trim();
    const sectionMatch = content.match(/##\s*(?:Theme|테마)[:\s]*(.+?)(?:\n|$)/i);
    if (sectionMatch && sectionMatch[1].trim())
      return sectionMatch[1].trim();
    return null;
  }
  async loadTodayLog() {
    const today = (0, import_obsidian.moment)().format("YYYY-MM-DD");
    const folder = this.plugin.settings.dailyNotesFolder;
    const filePath = `${folder}/${today}.md`;
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (file instanceof import_obsidian.TFile) {
      this.currentFile = file;
      const content = await this.app.vault.read(file);
      this.data = this.parseLogContent(content);
    } else {
      this.currentFile = null;
      this.data = this.getEmptyData();
      if (this.themes.length > 0) {
        this.data.theme = this.themes[0];
      }
    }
  }
  parseLogContent(content) {
    const data = this.getEmptyData();
    data.theme = this.extractTheme(content) || "";
    data.observations = this.extractSection(content, "Observations|\uAD00\uCC30");
    data.thoughts = this.extractSection(content, "Thoughts|\uC0DD\uAC01");
    data.questions = this.extractSection(content, "Questions|\uC758\uBB38\uC810|\uC9C8\uBB38");
    const dataSection = this.extractSection(content, "Data|\uB370\uC774\uD130|\uC218\uCE58");
    data.dataPoints = dataSection.map((line) => {
      const parts = line.split(":");
      return parts.length >= 2 ? { label: parts[0].trim(), value: parts.slice(1).join(":").trim() } : { label: line, value: "" };
    });
    const actionsMatch = content.match(/##\s*(?:Next Actions|Actions|액션|다음)[^#]*/i);
    if (actionsMatch) {
      const lines = actionsMatch[0].split("\n").slice(1);
      data.actions = lines.filter((line) => line.trim().match(/^-\s*\[[ x]\]/)).map((line) => ({
        text: line.replace(/^-\s*\[[ x]\]\s*/, "").trim(),
        completed: line.includes("[x]")
      }));
    }
    return data;
  }
  extractSection(content, sectionPattern) {
    const regex = new RegExp(`##\\s*(?:${sectionPattern})[^#]*`, "i");
    const match = content.match(regex);
    if (!match)
      return [];
    return match[0].split("\n").slice(1).filter((line) => line.trim().startsWith("-")).map((line) => line.replace(/^-\s*/, "").trim()).filter((line) => line.length > 0);
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("thinklog-input-container");
    this.injectStyles();
    const wrapper = container.createDiv({ cls: "tl-input-wrapper" });
    this.renderHeader(wrapper);
    this.renderThemeSelector(wrapper);
    this.renderQuickCapture(wrapper);
    wrapper.createEl("div", { cls: "tl-divider", text: "or add to specific section" });
    SECTIONS.forEach((section) => this.renderSection(wrapper, section));
    this.renderDataSection(wrapper);
    this.renderActionsSection(wrapper);
    this.renderFooter(wrapper);
  }
  renderHeader(container) {
    const header = container.createDiv({ cls: "tl-input-header" });
    const brand = header.createDiv({ cls: "tl-brand" });
    const icon = brand.createSpan({ cls: "tl-brand-icon" });
    (0, import_obsidian.setIcon)(icon, "layers");
    brand.createSpan({ text: "ThinkLog", cls: "tl-brand-text" });
    const dateDisplay = header.createDiv({ cls: "tl-date-display" });
    dateDisplay.createSpan({
      text: (0, import_obsidian.moment)().format("MMM DD, YYYY"),
      cls: "tl-date-badge"
    });
    dateDisplay.createSpan({
      text: (0, import_obsidian.moment)().format("dddd"),
      cls: "tl-date-relative"
    });
    const actions = header.createDiv({ cls: "tl-header-actions" });
    const saveBtn = actions.createEl("button", { cls: "tl-btn tl-btn-primary", text: "Save" });
    saveBtn.addEventListener("click", () => this.save());
  }
  renderThemeSelector(container) {
    const section = container.createDiv({ cls: "tl-theme-section" });
    const label = section.createDiv({ cls: "tl-section-label" });
    label.createSpan({ text: "\u{1F3AF}" });
    label.createSpan({ text: " Today's Theme" });
    const inputWrapper = section.createDiv({ cls: "tl-theme-input-wrapper" });
    const input = inputWrapper.createEl("input", {
      type: "text",
      cls: "tl-theme-input",
      placeholder: "Enter theme or select...",
      value: this.data.theme
    });
    input.addEventListener("input", (e) => {
      this.data.theme = e.target.value;
      this.scheduleAutosave();
    });
    const datalist = inputWrapper.createEl("datalist");
    datalist.id = "theme-suggestions";
    this.themes.forEach((theme) => {
      datalist.createEl("option", { value: theme });
    });
    input.setAttribute("list", "theme-suggestions");
    if (this.data.theme && this.themes.includes(this.data.theme)) {
      const linkedCount = this.themes.filter((t) => t === this.data.theme).length;
      section.createDiv({
        cls: "tl-theme-meta",
        text: `Linked to previous logs with this theme`
      });
    }
  }
  renderQuickCapture(container) {
    const section = container.createDiv({ cls: "tl-quick-capture" });
    const header = section.createDiv({ cls: "tl-quick-header" });
    header.createSpan({ text: "\u26A1 Quick Capture", cls: "tl-quick-title" });
    header.createSpan({
      text: "(AI will auto-categorize)",
      cls: "tl-quick-subtitle"
    });
    const textarea = section.createEl("textarea", {
      cls: "tl-quick-textarea",
      placeholder: "\uBB34\uC5C7\uC774\uB4E0 \uC801\uC5B4\uBCF4\uC138\uC694... \uB098\uC911\uC5D0 \uC139\uC158\uBCC4\uB85C \uC815\uB9AC\uD560 \uC218 \uC788\uC5B4\uC694."
    });
    textarea.value = this.data.quickCapture;
    textarea.addEventListener("input", (e) => {
      this.data.quickCapture = e.target.value;
      this.autoResizeTextarea(e.target);
      this.scheduleAutosave();
    });
    const parseBtn = section.createEl("button", {
      cls: "tl-btn tl-btn-secondary tl-parse-btn",
      text: "\u2192 Categorize to sections"
    });
    parseBtn.addEventListener("click", () => this.parseQuickCapture());
  }
  renderSection(container, config) {
    const section = container.createDiv({ cls: `tl-section tl-section-${config.id}` });
    section.style.setProperty("--section-color", config.color);
    const header = section.createDiv({ cls: "tl-section-header" });
    const iconEl = header.createSpan({ cls: "tl-section-icon" });
    (0, import_obsidian.setIcon)(iconEl, config.icon);
    const titleGroup = header.createDiv({ cls: "tl-section-title-group" });
    titleGroup.createDiv({ cls: "tl-section-title", text: `${config.titleKo} (${config.title})` });
    const prompt = config.prompts[Math.floor(Math.random() * config.prompts.length)];
    titleGroup.createDiv({ cls: "tl-section-prompt", text: `"${prompt}"` });
    const count = header.createSpan({
      cls: "tl-section-count",
      text: String(this.data[config.id].length)
    });
    const addBtn = header.createEl("button", { cls: "tl-btn tl-btn-icon" });
    (0, import_obsidian.setIcon)(addBtn, "plus");
    addBtn.addEventListener("click", () => this.addItem(config.id));
    const body = section.createDiv({ cls: "tl-section-body" });
    const items = this.data[config.id];
    items.forEach((item, index) => {
      this.renderItem(body, config.id, item, index);
    });
    const addNew = body.createDiv({ cls: "tl-add-new" });
    const addInput = addNew.createEl("input", {
      type: "text",
      cls: "tl-add-input",
      placeholder: config.placeholder
    });
    addInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && e.target.value.trim()) {
        this.addItemWithValue(config.id, e.target.value.trim());
        e.target.value = "";
      }
    });
  }
  renderItem(container, sectionId, value, index) {
    const item = container.createDiv({ cls: "tl-item" });
    const bullet = item.createSpan({ cls: "tl-item-bullet", text: "\u2022" });
    const input = item.createEl("input", {
      type: "text",
      cls: "tl-item-input",
      value
    });
    input.addEventListener("input", (e) => {
      this.data[sectionId][index] = e.target.value;
      this.scheduleAutosave();
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Backspace" && !e.target.value) {
        this.removeItem(sectionId, index);
      }
      if (e.key === "Enter") {
        this.addItem(sectionId);
      }
    });
    const deleteBtn = item.createEl("button", { cls: "tl-btn tl-btn-delete" });
    (0, import_obsidian.setIcon)(deleteBtn, "x");
    deleteBtn.addEventListener("click", () => this.removeItem(sectionId, index));
  }
  renderDataSection(container) {
    const section = container.createDiv({ cls: "tl-section tl-section-data" });
    section.style.setProperty("--section-color", "#10b981");
    const header = section.createDiv({ cls: "tl-section-header" });
    const iconEl = header.createSpan({ cls: "tl-section-icon" });
    (0, import_obsidian.setIcon)(iconEl, "bar-chart-2");
    const titleGroup = header.createDiv({ cls: "tl-section-title-group" });
    titleGroup.createDiv({ cls: "tl-section-title", text: "\u{1F4CA} \uB370\uC774\uD130 (Data Points)" });
    titleGroup.createDiv({ cls: "tl-section-prompt", text: '"\uAD00\uB828 \uC218\uCE58\uAC00 \uC788\uB098\uC694?"' });
    const addBtn = header.createEl("button", { cls: "tl-btn tl-btn-icon" });
    (0, import_obsidian.setIcon)(addBtn, "plus");
    addBtn.addEventListener("click", () => this.addDataPoint());
    const body = section.createDiv({ cls: "tl-section-body" });
    this.data.dataPoints.forEach((dp, index) => {
      const item = body.createDiv({ cls: "tl-data-item" });
      const labelInput = item.createEl("input", {
        type: "text",
        cls: "tl-data-label",
        placeholder: "\uD56D\uBAA9\uBA85",
        value: dp.label
      });
      item.createSpan({ cls: "tl-data-separator", text: ":" });
      const valueInput = item.createEl("input", {
        type: "text",
        cls: "tl-data-value",
        placeholder: "\uAC12",
        value: dp.value
      });
      labelInput.addEventListener("input", (e) => {
        this.data.dataPoints[index].label = e.target.value;
        this.scheduleAutosave();
      });
      valueInput.addEventListener("input", (e) => {
        this.data.dataPoints[index].value = e.target.value;
        this.scheduleAutosave();
      });
      const deleteBtn = item.createEl("button", { cls: "tl-btn tl-btn-delete" });
      (0, import_obsidian.setIcon)(deleteBtn, "x");
      deleteBtn.addEventListener("click", () => {
        this.data.dataPoints.splice(index, 1);
        this.render();
        this.scheduleAutosave();
      });
    });
    const addNew = body.createDiv({ cls: "tl-data-item tl-add-new" });
    const newLabel = addNew.createEl("input", {
      type: "text",
      cls: "tl-data-label",
      placeholder: "\uC0C8 \uD56D\uBAA9..."
    });
    addNew.createSpan({ cls: "tl-data-separator", text: ":" });
    const newValue = addNew.createEl("input", {
      type: "text",
      cls: "tl-data-value",
      placeholder: "\uAC12"
    });
    const handleAdd = () => {
      if (newLabel.value.trim()) {
        this.data.dataPoints.push({
          label: newLabel.value.trim(),
          value: newValue.value.trim()
        });
        this.render();
        this.scheduleAutosave();
      }
    };
    newLabel.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        handleAdd();
    });
    newValue.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        handleAdd();
    });
  }
  renderActionsSection(container) {
    const section = container.createDiv({ cls: "tl-section tl-section-actions" });
    section.style.setProperty("--section-color", "#f59e0b");
    const header = section.createDiv({ cls: "tl-section-header" });
    const iconEl = header.createSpan({ cls: "tl-section-icon" });
    (0, import_obsidian.setIcon)(iconEl, "check-square");
    const titleGroup = header.createDiv({ cls: "tl-section-title-group" });
    titleGroup.createDiv({ cls: "tl-section-title", text: "\u2705 \uB2E4\uC74C \uC561\uC158 (Next Actions)" });
    titleGroup.createDiv({ cls: "tl-section-prompt", text: '"\uB2E4\uC74C\uC5D0 \uD574\uC57C \uD560 \uC77C\uC740?"' });
    const addBtn = header.createEl("button", { cls: "tl-btn tl-btn-icon" });
    (0, import_obsidian.setIcon)(addBtn, "plus");
    addBtn.addEventListener("click", () => this.addActionItem());
    const body = section.createDiv({ cls: "tl-section-body" });
    this.data.actions.forEach((action, index) => {
      const item = body.createDiv({ cls: "tl-action-item" });
      const checkbox = item.createEl("input", {
        type: "checkbox",
        cls: "tl-action-checkbox"
      });
      checkbox.checked = action.completed;
      checkbox.addEventListener("change", (e) => {
        this.data.actions[index].completed = e.target.checked;
        this.scheduleAutosave();
      });
      const input = item.createEl("input", {
        type: "text",
        cls: "tl-action-input",
        value: action.text
      });
      if (action.completed)
        input.addClass("completed");
      input.addEventListener("input", (e) => {
        this.data.actions[index].text = e.target.value;
        this.scheduleAutosave();
      });
      const deleteBtn = item.createEl("button", { cls: "tl-btn tl-btn-delete" });
      (0, import_obsidian.setIcon)(deleteBtn, "x");
      deleteBtn.addEventListener("click", () => {
        this.data.actions.splice(index, 1);
        this.render();
        this.scheduleAutosave();
      });
    });
    const addNew = body.createDiv({ cls: "tl-action-item tl-add-new" });
    const newCheckbox = addNew.createEl("input", { type: "checkbox", cls: "tl-action-checkbox" });
    newCheckbox.disabled = true;
    const newInput = addNew.createEl("input", {
      type: "text",
      cls: "tl-action-input",
      placeholder: "\uC0C8 \uC561\uC158 \uCD94\uAC00..."
    });
    newInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && e.target.value.trim()) {
        this.data.actions.push({
          text: e.target.value.trim(),
          completed: false
        });
        this.render();
        this.scheduleAutosave();
      }
    });
  }
  renderFooter(container) {
    const footer = container.createDiv({ cls: "tl-input-footer" });
    const stats = footer.createDiv({ cls: "tl-footer-stats" });
    const totalItems = this.data.observations.length + this.data.thoughts.length + this.data.questions.length + this.data.dataPoints.length + this.data.actions.length;
    stats.createSpan({ text: `\u{1F4A1} Tip: Cmd+S to save | ` });
    stats.createSpan({ text: `${totalItems} items today` });
    const streakBadge = footer.createDiv({ cls: "tl-streak-badge" });
    streakBadge.createSpan({ text: "\u{1F525}" });
    streakBadge.createSpan({ text: " 3 day streak" });
  }
  // Actions
  addItem(sectionId) {
    this.data[sectionId].push("");
    this.render();
    setTimeout(() => {
      const inputs = this.containerEl.querySelectorAll(`.tl-section-${sectionId} .tl-item-input`);
      const lastInput = inputs[inputs.length - 1];
      lastInput == null ? void 0 : lastInput.focus();
    }, 10);
  }
  addItemWithValue(sectionId, value) {
    this.data[sectionId].push(value);
    this.render();
    this.scheduleAutosave();
  }
  removeItem(sectionId, index) {
    this.data[sectionId].splice(index, 1);
    this.render();
    this.scheduleAutosave();
  }
  addDataPoint() {
    this.data.dataPoints.push({ label: "", value: "" });
    this.render();
  }
  addActionItem() {
    this.data.actions.push({ text: "", completed: false });
    this.render();
  }
  parseQuickCapture() {
    const text = this.data.quickCapture.trim();
    if (!text)
      return;
    const lines = text.split("\n").filter((l) => l.trim());
    lines.forEach((line) => {
      const trimmed = line.trim();
      if (trimmed.endsWith("?") || trimmed.includes("\uC5B4\uB5BB\uAC8C") || trimmed.includes("\uC65C")) {
        this.data.questions.push(trimmed);
      } else if (trimmed.match(/\d+[%억원명개월]/) || trimmed.includes(":")) {
        const parts = trimmed.split(":");
        if (parts.length >= 2) {
          this.data.dataPoints.push({ label: parts[0].trim(), value: parts.slice(1).join(":").trim() });
        } else {
          this.data.dataPoints.push({ label: trimmed, value: "" });
        }
      } else if (trimmed.includes("\uD574\uC57C") || trimmed.includes("\uD544\uC694") || trimmed.includes("\uC608\uC815")) {
        this.data.actions.push({ text: trimmed, completed: false });
      } else if (trimmed.includes("\uAC83 \uAC19") || trimmed.includes("\uC0DD\uAC01") || trimmed.includes("\uB290\uB08C")) {
        this.data.thoughts.push(trimmed);
      } else {
        this.data.observations.push(trimmed);
      }
    });
    this.data.quickCapture = "";
    this.render();
    this.scheduleAutosave();
    new import_obsidian.Notice(`${lines.length} items categorized`);
  }
  autoResizeTextarea(textarea) {
    textarea.style.height = "auto";
    textarea.style.height = textarea.scrollHeight + "px";
  }
  scheduleAutosave() {
    if (this.saveTimeout) {
      clearTimeout(this.saveTimeout);
    }
    this.saveTimeout = setTimeout(() => this.save(), 2e3);
  }
  async save() {
    if (!this.data.theme) {
      new import_obsidian.Notice("Please enter a theme first");
      return;
    }
    const today = (0, import_obsidian.moment)().format("YYYY-MM-DD");
    const folder = this.plugin.settings.dailyNotesFolder;
    const filePath = `${folder}/${today}.md`;
    const content = this.generateMarkdown();
    let file = this.app.vault.getAbstractFileByPath(filePath);
    if (file instanceof import_obsidian.TFile) {
      await this.app.vault.modify(file, content);
    } else {
      if (!this.app.vault.getAbstractFileByPath(folder)) {
        await this.app.vault.createFolder(folder);
      }
      await this.app.vault.create(filePath, content);
    }
    new import_obsidian.Notice("Saved!");
  }
  generateMarkdown() {
    const today = (0, import_obsidian.moment)().format("YYYY-MM-DD");
    let md = `---
date: ${today}
tags: [thinklog, daily]
theme: ${this.data.theme}
---

# ${today} Daily Log

## Theme: ${this.data.theme}

`;
    if (this.data.observations.length > 0) {
      md += `### Observations
`;
      this.data.observations.forEach((o) => {
        if (o)
          md += `- ${o}
`;
      });
      md += "\n";
    }
    if (this.data.thoughts.length > 0) {
      md += `### Thoughts
`;
      this.data.thoughts.forEach((t) => {
        if (t)
          md += `- ${t}
`;
      });
      md += "\n";
    }
    if (this.data.questions.length > 0) {
      md += `### Questions
`;
      this.data.questions.forEach((q) => {
        if (q)
          md += `- ${q}
`;
      });
      md += "\n";
    }
    if (this.data.dataPoints.length > 0) {
      md += `### Data Points
`;
      this.data.dataPoints.forEach((d) => {
        if (d.label)
          md += `- ${d.label}: ${d.value}
`;
      });
      md += "\n";
    }
    if (this.data.actions.length > 0) {
      md += `### Next Actions
`;
      this.data.actions.forEach((a) => {
        if (a.text)
          md += `- [${a.completed ? "x" : " "}] ${a.text}
`;
      });
      md += "\n";
    }
    md += `---
#thinklog
`;
    return md;
  }
  injectStyles() {
    const styleId = "thinklog-input-styles";
    if (document.getElementById(styleId))
      return;
    const style = document.createElement("style");
    style.id = styleId;
    style.textContent = INPUT_VIEW_STYLES;
    document.head.appendChild(style);
  }
};
var INPUT_VIEW_STYLES = `
.thinklog-input-container {
  height: 100%;
  overflow: hidden;
}

.tl-input-wrapper {
  height: 100%;
  overflow-y: auto;
  padding: 0;
  background: var(--background-primary);
}

/* Header */
.tl-input-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 20px;
  border-bottom: 1px solid var(--background-modifier-border);
  background: var(--background-secondary);
  position: sticky;
  top: 0;
  z-index: 10;
}

.tl-brand {
  display: flex;
  align-items: center;
  gap: 8px;
}

.tl-brand-icon {
  color: var(--interactive-accent);
}

.tl-brand-text {
  font-weight: 600;
  font-size: 15px;
}

.tl-date-display {
  display: flex;
  align-items: center;
  gap: 10px;
}

.tl-date-badge {
  background: var(--text-normal);
  color: var(--background-primary);
  padding: 4px 10px;
  border-radius: 4px;
  font-size: 12px;
  font-weight: 600;
}

.tl-date-relative {
  font-size: 13px;
  color: var(--text-muted);
}

.tl-header-actions {
  display: flex;
  gap: 8px;
}

/* Buttons */
.tl-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  padding: 8px 14px;
  border-radius: 6px;
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  border: none;
  transition: all 0.15s ease;
  background: var(--background-secondary);
  color: var(--text-muted);
}

.tl-btn:hover {
  background: var(--background-modifier-hover);
  color: var(--text-normal);
}

.tl-btn-primary {
  background: var(--interactive-accent);
  color: white;
}

.tl-btn-primary:hover {
  background: var(--interactive-accent-hover);
  color: white;
}

.tl-btn-secondary {
  background: var(--background-secondary);
  border: 1px solid var(--background-modifier-border);
}

.tl-btn-icon {
  width: 28px;
  height: 28px;
  padding: 0;
}

.tl-btn-delete {
  width: 24px;
  height: 24px;
  padding: 0;
  opacity: 0;
  color: var(--text-error);
  background: transparent;
}

.tl-item:hover .tl-btn-delete,
.tl-data-item:hover .tl-btn-delete,
.tl-action-item:hover .tl-btn-delete {
  opacity: 1;
}

/* Theme Section */
.tl-theme-section {
  padding: 16px 20px;
  border-bottom: 1px solid var(--background-modifier-border);
}

.tl-section-label {
  font-size: 12px;
  font-weight: 600;
  color: var(--text-muted);
  margin-bottom: 10px;
  display: flex;
  align-items: center;
  gap: 4px;
}

.tl-theme-input-wrapper {
  position: relative;
}

.tl-theme-input {
  width: 100%;
  padding: 12px 14px;
  border: 2px solid var(--background-modifier-border);
  border-radius: 8px;
  font-size: 15px;
  font-weight: 500;
  background: var(--background-primary);
  color: var(--text-normal);
  transition: border-color 0.15s ease;
}

.tl-theme-input:focus {
  outline: none;
  border-color: var(--interactive-accent);
}

.tl-theme-meta {
  font-size: 12px;
  color: var(--text-muted);
  margin-top: 8px;
}

/* Quick Capture */
.tl-quick-capture {
  padding: 16px 20px;
  background: var(--background-secondary);
  border-bottom: 1px solid var(--background-modifier-border);
}

.tl-quick-header {
  margin-bottom: 10px;
}

.tl-quick-title {
  font-weight: 600;
  font-size: 13px;
}

.tl-quick-subtitle {
  font-size: 12px;
  color: var(--text-muted);
  margin-left: 8px;
}

.tl-quick-textarea {
  width: 100%;
  min-height: 80px;
  padding: 12px;
  border: 1px solid var(--background-modifier-border);
  border-radius: 8px;
  font-size: 14px;
  font-family: inherit;
  background: var(--background-primary);
  color: var(--text-normal);
  resize: vertical;
  line-height: 1.5;
}

.tl-quick-textarea:focus {
  outline: none;
  border-color: var(--interactive-accent);
}

.tl-parse-btn {
  margin-top: 10px;
  width: 100%;
}

/* Divider */
.tl-divider {
  text-align: center;
  padding: 16px 20px;
  font-size: 12px;
  color: var(--text-faint);
  position: relative;
}

.tl-divider::before,
.tl-divider::after {
  content: "";
  position: absolute;
  top: 50%;
  width: 60px;
  height: 1px;
  background: var(--background-modifier-border);
}

.tl-divider::before { left: 20px; }
.tl-divider::after { right: 20px; }

/* Sections */
.tl-section {
  padding: 16px 20px;
  border-bottom: 1px solid var(--background-modifier-border);
}

.tl-section-header {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 12px;
}

.tl-section-icon {
  width: 28px;
  height: 28px;
  border-radius: 6px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: color-mix(in srgb, var(--section-color) 15%, transparent);
  color: var(--section-color);
}

.tl-section-title-group {
  flex: 1;
}

.tl-section-title {
  font-size: 13px;
  font-weight: 600;
}

.tl-section-prompt {
  font-size: 12px;
  color: var(--text-muted);
  font-style: italic;
}

.tl-section-count {
  font-size: 11px;
  font-weight: 600;
  padding: 2px 8px;
  border-radius: 10px;
  background: var(--background-secondary);
  color: var(--text-muted);
}

/* Items */
.tl-section-body {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.tl-item {
  display: flex;
  align-items: center;
  gap: 8px;
}

.tl-item-bullet {
  width: 20px;
  text-align: center;
  color: var(--section-color);
  font-weight: bold;
}

.tl-item-input,
.tl-add-input {
  flex: 1;
  padding: 8px 10px;
  border: 1px solid transparent;
  border-radius: 6px;
  font-size: 14px;
  background: var(--background-secondary);
  color: var(--text-normal);
  transition: all 0.15s ease;
}

.tl-item-input:focus,
.tl-add-input:focus {
  outline: none;
  border-color: var(--section-color);
  background: var(--background-primary);
}

.tl-add-input::placeholder {
  color: var(--text-faint);
}

.tl-add-new {
  opacity: 0.7;
}

.tl-add-new:focus-within {
  opacity: 1;
}

/* Data Items */
.tl-data-item {
  display: flex;
  align-items: center;
  gap: 8px;
}

.tl-data-label {
  flex: 1;
  padding: 8px 10px;
  border: 1px solid transparent;
  border-radius: 6px 0 0 6px;
  font-size: 14px;
  background: var(--background-secondary);
  color: var(--text-normal);
}

.tl-data-separator {
  color: var(--text-muted);
  font-weight: 600;
}

.tl-data-value {
  width: 120px;
  padding: 8px 10px;
  border: 1px solid transparent;
  border-radius: 0 6px 6px 0;
  font-size: 14px;
  font-weight: 600;
  text-align: right;
  background: var(--background-secondary);
  color: var(--text-normal);
}

.tl-data-label:focus,
.tl-data-value:focus {
  outline: none;
  border-color: var(--section-color);
}

/* Action Items */
.tl-action-item {
  display: flex;
  align-items: center;
  gap: 10px;
}

.tl-action-checkbox {
  width: 18px;
  height: 18px;
  cursor: pointer;
  accent-color: var(--interactive-accent);
}

.tl-action-input {
  flex: 1;
  padding: 8px 10px;
  border: 1px solid transparent;
  border-radius: 6px;
  font-size: 14px;
  background: var(--background-secondary);
  color: var(--text-normal);
}

.tl-action-input.completed {
  text-decoration: line-through;
  color: var(--text-muted);
}

.tl-action-input:focus {
  outline: none;
  border-color: var(--section-color);
}

/* Footer */
.tl-input-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 20px;
  background: var(--background-secondary);
  border-top: 1px solid var(--background-modifier-border);
  position: sticky;
  bottom: 0;
}

.tl-footer-stats {
  font-size: 12px;
  color: var(--text-muted);
}

.tl-streak-badge {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 12px;
  font-weight: 600;
  color: var(--text-accent);
}
`;

// src/main.ts
var DEFAULT_SETTINGS = {
  defaultFramework: "mcksey",
  dailyNotesFolder: "daily",
  outputFolder: "thinklog/output",
  language: "ko",
  showStreak: true,
  aiEnabled: false
};
var VIEW_TYPE_THINKLOG = "thinklog-view";
var ThinkLogPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_THINKLOG, (leaf) => new ThinkLogView(leaf, this));
    this.registerView(VIEW_TYPE_THINKLOG_INPUT, (leaf) => new ThinkLogInputView(leaf, this));
    this.addRibbonIcon("edit-3", "ThinkLog Input", () => {
      this.activateInputView();
    });
    this.addRibbonIcon("layers", "ThinkLog Dashboard", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-thinklog",
      name: "Open ThinkLog Dashboard",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "open-thinklog-input",
      name: "Open ThinkLog Input (Quick Capture)",
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "t" }],
      callback: () => this.activateInputView()
    });
    this.addCommand({
      id: "new-thinklog-entry",
      name: "New ThinkLog Entry (Markdown)",
      callback: () => this.createNewEntry()
    });
    this.addCommand({
      id: "generate-report",
      name: "Generate Report from Theme",
      callback: () => this.showReportModal()
    });
    this.addSettingTab(new ThinkLogSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
    });
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_THINKLOG);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      await (leaf == null ? void 0 : leaf.setViewState({ type: VIEW_TYPE_THINKLOG, active: true }));
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async activateInputView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_THINKLOG_INPUT);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getLeaf("tab");
      await (leaf == null ? void 0 : leaf.setViewState({ type: VIEW_TYPE_THINKLOG_INPUT, active: true }));
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async createNewEntry() {
    const today = (0, import_obsidian2.moment)().format("YYYY-MM-DD");
    const folder = this.settings.dailyNotesFolder;
    const filePath = `${folder}/${today}.md`;
    let file = this.app.vault.getAbstractFileByPath(filePath);
    if (!file) {
      const template = this.getEntryTemplate(today);
      await this.app.vault.create(filePath, template);
      new import_obsidian2.Notice(`Created new ThinkLog entry: ${today}`);
    }
    file = this.app.vault.getAbstractFileByPath(filePath);
    if (file instanceof import_obsidian2.TFile) {
      const leaf = this.app.workspace.getLeaf();
      await leaf.openFile(file);
    }
  }
  getEntryTemplate(date) {
    return `---
date: ${date}
tags: [thinklog, daily]
theme:
---

# ${date} Daily Log

## Theme
<!-- Today's focus topic -->


## Observations
<!-- Facts - what you saw and heard -->
-

## Thoughts
<!-- Ideas, opinions, judgments -->
-

## Questions
<!-- What you're curious about, what needs verification -->
-

## Data Points
<!-- Numbers, statistics, measurements -->
-

## Next Actions
<!-- What needs to be done -->
- [ ]

---
#thinklog
`;
  }
  async showReportModal() {
    new import_obsidian2.Notice("Report generation modal - Coming soon!");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var ThinkLogView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentEntry = null;
    this.themes = [];
    this.selectedTheme = "";
    this.streak = 0;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_THINKLOG;
  }
  getDisplayText() {
    return "ThinkLog";
  }
  getIcon() {
    return "layers";
  }
  async onOpen() {
    await this.loadThemes();
    await this.calculateStreak();
    this.render();
  }
  async onClose() {
  }
  async loadThemes() {
    const files = this.app.vault.getMarkdownFiles();
    const themeMap = /* @__PURE__ */ new Map();
    for (const file of files) {
      if (file.path.includes(this.plugin.settings.dailyNotesFolder)) {
        const content = await this.app.vault.read(file);
        const theme = this.extractTheme(content);
        if (theme) {
          if (!themeMap.has(theme)) {
            themeMap.set(theme, {
              name: theme,
              emoji: this.getThemeEmoji(theme),
              logCount: 0,
              startDate: file.basename,
              lastLog: file.basename
            });
          }
          const info = themeMap.get(theme);
          info.logCount++;
          if (file.basename > info.lastLog)
            info.lastLog = file.basename;
          if (file.basename < info.startDate)
            info.startDate = file.basename;
        }
      }
    }
    this.themes = Array.from(themeMap.values());
    if (this.themes.length > 0 && !this.selectedTheme) {
      this.selectedTheme = this.themes[0].name;
    }
  }
  extractTheme(content) {
    const fmMatch = content.match(/^---\n[\s\S]*?theme:\s*(.+?)\n[\s\S]*?---/m);
    if (fmMatch && fmMatch[1].trim()) {
      return fmMatch[1].trim();
    }
    const sectionMatch = content.match(/##\s*(?:Theme|테마)[:\s]*(.+?)(?:\n|$)/i);
    if (sectionMatch && sectionMatch[1].trim()) {
      return sectionMatch[1].trim();
    }
    return null;
  }
  getThemeEmoji(theme) {
    const emojiMap = {
      "\uB514\uC9C0\uD138": "\u{1F680}",
      "\uC804\uD658": "\u{1F504}",
      "OKR": "\u{1F4CA}",
      "\uAE30\uD68D": "\u{1F4A1}",
      "\uAC1C\uBC1C": "\u{1F4BB}",
      "\uB9C8\uCF00\uD305": "\u{1F4E3}",
      "\uC601\uC5C5": "\u{1F4BC}"
    };
    for (const [key, emoji] of Object.entries(emojiMap)) {
      if (theme.includes(key))
        return emoji;
    }
    return "\u{1F4DD}";
  }
  async calculateStreak() {
    const files = this.app.vault.getMarkdownFiles().filter((f) => f.path.includes(this.plugin.settings.dailyNotesFolder)).map((f) => f.basename).filter((n) => /^\d{4}-\d{2}-\d{2}$/.test(n)).sort().reverse();
    let streak = 0;
    let checkDate = (0, import_obsidian2.moment)();
    for (const filename of files) {
      const fileDate = (0, import_obsidian2.moment)(filename, "YYYY-MM-DD");
      if (fileDate.isSame(checkDate, "day")) {
        streak++;
        checkDate = checkDate.subtract(1, "day");
      } else if (fileDate.isBefore(checkDate, "day")) {
        break;
      }
    }
    this.streak = streak;
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("thinklog-container");
    this.injectStyles();
    container.innerHTML = this.buildHTML();
    this.attachEventListeners(container);
  }
  injectStyles() {
    const styleId = "thinklog-styles";
    if (!document.getElementById(styleId)) {
      const style = document.createElement("style");
      style.id = styleId;
      style.textContent = THINKLOG_STYLES;
      document.head.appendChild(style);
    }
  }
  buildHTML() {
    const today = (0, import_obsidian2.moment)().format("MMM DD, YYYY");
    const dayName = (0, import_obsidian2.moment)().format("dddd");
    return `
      <div class="tl-panel">
        <!-- Header -->
        <div class="tl-header">
          <div class="tl-brand">
            <svg class="tl-logo" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/>
            </svg>
            <span>ThinkLog</span>
          </div>
          <button class="tl-btn tl-btn-icon" data-action="new-entry" title="New Entry">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M12 5v14M5 12h14"/>
            </svg>
          </button>
        </div>

        <!-- Date Display -->
        <div class="tl-date-section">
          <span class="tl-date-badge">${today}</span>
          <span class="tl-date-relative">${dayName}</span>
        </div>

        <!-- Streak -->
        ${this.plugin.settings.showStreak ? `
        <div class="tl-streak-card">
          <div class="tl-streak-number">${this.streak}</div>
          <div class="tl-streak-label">Day Streak \u{1F525}</div>
        </div>
        ` : ""}

        <!-- Theme Selector -->
        <div class="tl-section">
          <div class="tl-section-label">Current Theme</div>
          <div class="tl-theme-list">
            ${this.themes.map((theme) => `
              <div class="tl-theme-option ${theme.name === this.selectedTheme ? "active" : ""}"
                   data-theme="${theme.name}">
                <div class="tl-theme-icon">${theme.emoji}</div>
                <div class="tl-theme-info">
                  <div class="tl-theme-name">${theme.name}</div>
                  <div class="tl-theme-meta">${theme.logCount} logs \xB7 Started ${theme.startDate}</div>
                </div>
              </div>
            `).join("")}
            <button class="tl-new-theme-btn" data-action="new-theme">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M12 5v14M5 12h14"/>
              </svg>
              New Theme
            </button>
          </div>
        </div>

        <!-- Quick Actions -->
        <div class="tl-section">
          <div class="tl-section-label">Quick Actions</div>
          <div class="tl-action-grid">
            <button class="tl-action-btn" data-action="today-log">
              <span class="tl-action-icon">\u{1F4DD}</span>
              <span>Today's Log</span>
            </button>
            <button class="tl-action-btn" data-action="generate-report">
              <span class="tl-action-icon">\u{1F4CA}</span>
              <span>Generate Report</span>
            </button>
            <button class="tl-action-btn" data-action="view-logs">
              <span class="tl-action-icon">\u{1F4DA}</span>
              <span>View All Logs</span>
            </button>
            <button class="tl-action-btn" data-action="export-html">
              <span class="tl-action-icon">\u{1F3A8}</span>
              <span>Export HTML</span>
            </button>
          </div>
        </div>

        <!-- Stats -->
        <div class="tl-section">
          <div class="tl-section-label">Statistics</div>
          <div class="tl-stats-grid">
            <div class="tl-stat">
              <div class="tl-stat-value">${this.themes.reduce((sum, t) => sum + t.logCount, 0)}</div>
              <div class="tl-stat-label">Total Logs</div>
            </div>
            <div class="tl-stat">
              <div class="tl-stat-value">${this.themes.length}</div>
              <div class="tl-stat-label">Themes</div>
            </div>
            <div class="tl-stat">
              <div class="tl-stat-value">${this.streak}</div>
              <div class="tl-stat-label">Streak</div>
            </div>
          </div>
        </div>

        <!-- Footer -->
        <div class="tl-footer">
          <button class="tl-btn tl-btn-primary" data-action="new-entry">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M12 5v14M5 12h14"/>
            </svg>
            New Entry
          </button>
        </div>
      </div>
    `;
  }
  attachEventListeners(container) {
    container.querySelectorAll(".tl-theme-option").forEach((el) => {
      el.addEventListener("click", (e) => {
        const theme = e.currentTarget.dataset.theme;
        if (theme) {
          this.selectedTheme = theme;
          this.render();
        }
      });
    });
    container.querySelectorAll("[data-action]").forEach((el) => {
      el.addEventListener("click", (e) => {
        const action = e.currentTarget.dataset.action;
        this.handleAction(action || "");
      });
    });
  }
  async handleAction(action) {
    switch (action) {
      case "new-entry":
      case "today-log":
        await this.plugin.createNewEntry();
        break;
      case "generate-report":
        await this.generateReport();
        break;
      case "view-logs":
        this.viewAllLogs();
        break;
      case "export-html":
        await this.exportHTML();
        break;
      case "new-theme":
        new import_obsidian2.Notice("Enter theme in today's log frontmatter");
        await this.plugin.createNewEntry();
        break;
    }
  }
  async generateReport() {
    if (!this.selectedTheme) {
      new import_obsidian2.Notice("Please select a theme first");
      return;
    }
    const logs = await this.collectLogsForTheme(this.selectedTheme);
    if (logs.length === 0) {
      new import_obsidian2.Notice("No logs found for this theme");
      return;
    }
    const report = this.buildReport(logs, this.selectedTheme);
    const fileName = `${this.selectedTheme.replace(/\s+/g, "_")}_report_${(0, import_obsidian2.moment)().format("YYYYMMDD_HHmm")}.md`;
    const filePath = `${this.plugin.settings.outputFolder}/${fileName}`;
    const folder = this.plugin.settings.outputFolder;
    if (!this.app.vault.getAbstractFileByPath(folder)) {
      await this.app.vault.createFolder(folder);
    }
    await this.app.vault.create(filePath, report);
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (file instanceof import_obsidian2.TFile) {
      const leaf = this.app.workspace.getLeaf();
      await leaf.openFile(file);
    }
    new import_obsidian2.Notice(`Report generated: ${fileName}`);
  }
  async collectLogsForTheme(theme) {
    const files = this.app.vault.getMarkdownFiles().filter((f) => f.path.includes(this.plugin.settings.dailyNotesFolder)).sort((a, b) => a.basename.localeCompare(b.basename));
    const logs = [];
    for (const file of files) {
      const content = await this.app.vault.read(file);
      const fileTheme = this.extractTheme(content);
      if (fileTheme === theme) {
        logs.push(this.parseLog(content, file.basename));
      }
    }
    return logs;
  }
  parseLog(content, date) {
    const entry = {
      date,
      theme: this.extractTheme(content) || "",
      observations: this.extractSection(content, "Observations|\uAD00\uCC30"),
      thoughts: this.extractSection(content, "Thoughts|\uC0DD\uAC01"),
      questions: this.extractSection(content, "Questions|\uC758\uBB38\uC810"),
      dataPoints: this.extractDataPoints(content),
      actions: this.extractActions(content)
    };
    return entry;
  }
  extractSection(content, sectionPattern) {
    const regex = new RegExp(`##\\s*(?:${sectionPattern})[^#]*`, "i");
    const match = content.match(regex);
    if (!match)
      return [];
    const lines = match[0].split("\n").slice(1);
    return lines.filter((line) => line.trim().startsWith("-")).map((line) => line.replace(/^-\s*/, "").trim()).filter((line) => line.length > 0);
  }
  extractDataPoints(content) {
    const section = this.extractSection(content, "Data|\uB370\uC774\uD130|\uC218\uCE58");
    return section.map((line) => {
      const parts = line.split(":");
      if (parts.length >= 2) {
        return { label: parts[0].trim(), value: parts.slice(1).join(":").trim() };
      }
      return { label: line, value: "" };
    });
  }
  extractActions(content) {
    const regex = /##\s*(?:Next Actions|액션|다음)[^#]*/i;
    const match = content.match(regex);
    if (!match)
      return [];
    const lines = match[0].split("\n").slice(1);
    return lines.filter((line) => line.trim().match(/^-\s*\[[ x]\]/)).map((line) => ({
      text: line.replace(/^-\s*\[[ x]\]\s*/, "").trim(),
      completed: line.includes("[x]")
    }));
  }
  buildReport(logs, theme) {
    const allObservations = logs.flatMap((l) => l.observations);
    const allThoughts = logs.flatMap((l) => l.thoughts);
    const allQuestions = logs.flatMap((l) => l.questions);
    const allData = logs.flatMap((l) => l.dataPoints);
    const allActions = logs.flatMap((l) => l.actions);
    const dateRange = `${logs[0].date} ~ ${logs[logs.length - 1].date}`;
    return `# ${theme}
### McKinsey MECE Analysis Report

**Generated**: ${(0, import_obsidian2.moment)().format("YYYY-MM-DD HH:mm")}
**Analysis Period**: ${dateRange} (${logs.length} days)

---

## Executive Summary

This report analyzes **${theme}** based on ${logs.length} daily logs containing ${allObservations.length} observations and ${allData.length} data points.

Key findings include: ${allThoughts.slice(0, 3).join(", ")}.

Recommended actions: ${allActions.filter((a) => !a.completed).slice(0, 3).map((a) => a.text).join(", ")}.

---

## 1. Situation Analysis

${allObservations.map((o) => `- ${o}`).join("\n")}

## 2. Key Insights

${allThoughts.map((t) => `- ${t}`).join("\n")}

## 3. Open Questions

${allQuestions.map((q) => `- ${q}`).join("\n")}

## 4. Data Points

| Metric | Value |
|--------|-------|
${allData.map((d) => `| ${d.label} | ${d.value} |`).join("\n")}

## 5. Recommended Actions

${allActions.map((a) => `- [${a.completed ? "x" : " "}] ${a.text}`).join("\n")}

---

*Generated by ThinkLog*
`;
  }
  viewAllLogs() {
    var _a, _b, _c, _d;
    const folder = this.plugin.settings.dailyNotesFolder;
    const file = this.app.vault.getAbstractFileByPath(folder);
    if (file) {
      (_d = (_c = (_b = (_a = this.app.internalPlugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b["file-explorer"]) == null ? void 0 : _c.instance) == null ? void 0 : _d.revealInFolder(file);
    }
  }
  async exportHTML() {
    if (!this.selectedTheme) {
      new import_obsidian2.Notice("Please select a theme first");
      return;
    }
    const logs = await this.collectLogsForTheme(this.selectedTheme);
    if (logs.length === 0) {
      new import_obsidian2.Notice("No logs found for this theme");
      return;
    }
    const html = this.buildHTMLReport(logs, this.selectedTheme);
    const fileName = `${this.selectedTheme.replace(/\s+/g, "_")}_${(0, import_obsidian2.moment)().format("YYYYMMDD_HHmm")}.html`;
    const filePath = `${this.plugin.settings.outputFolder}/${fileName}`;
    const folder = this.plugin.settings.outputFolder;
    if (!this.app.vault.getAbstractFileByPath(folder)) {
      await this.app.vault.createFolder(folder);
    }
    await this.app.vault.create(filePath, html);
    new import_obsidian2.Notice(`HTML report exported: ${fileName}`);
  }
  buildHTMLReport(logs, theme) {
    const allData = logs.flatMap((l) => l.dataPoints);
    return `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>${theme} - ThinkLog Report</title>
  <style>
    :root { --accent: #2563eb; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, sans-serif; background: #fafafa; color: #171717; line-height: 1.6; padding: 48px; }
    .container { max-width: 900px; margin: 0 auto; }
    h1 { font-size: 32px; margin-bottom: 8px; }
    .meta { color: #737373; font-size: 14px; margin-bottom: 32px; }
    .card { background: white; border: 1px solid #e5e5e5; border-radius: 12px; padding: 24px; margin-bottom: 24px; }
    .card h2 { font-size: 18px; color: var(--accent); margin-bottom: 16px; }
    ul { padding-left: 20px; }
    li { margin-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; }
    th, td { text-align: left; padding: 12px; border-bottom: 1px solid #e5e5e5; }
    th { font-weight: 600; color: #737373; font-size: 12px; text-transform: uppercase; }
  </style>
</head>
<body>
  <div class="container">
    <h1>${theme}</h1>
    <div class="meta">Generated ${(0, import_obsidian2.moment)().format("YYYY-MM-DD")} \xB7 ${logs.length} days analyzed</div>

    <div class="card">
      <h2>Key Observations</h2>
      <ul>
        ${logs.flatMap((l) => l.observations).map((o) => `<li>${o}</li>`).join("")}
      </ul>
    </div>

    <div class="card">
      <h2>Insights</h2>
      <ul>
        ${logs.flatMap((l) => l.thoughts).map((t) => `<li>${t}</li>`).join("")}
      </ul>
    </div>

    <div class="card">
      <h2>Data Points</h2>
      <table>
        <thead><tr><th>Metric</th><th>Value</th></tr></thead>
        <tbody>
          ${allData.map((d) => `<tr><td>${d.label}</td><td>${d.value}</td></tr>`).join("")}
        </tbody>
      </table>
    </div>

    <div class="card">
      <h2>Next Actions</h2>
      <ul>
        ${logs.flatMap((l) => l.actions).map((a) => `<li>${a.completed ? "\u2705" : "\u2B1C"} ${a.text}</li>`).join("")}
      </ul>
    </div>
  </div>
</body>
</html>`;
  }
};
var ThinkLogSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "ThinkLog Settings" });
    new import_obsidian2.Setting(containerEl).setName("Daily Notes Folder").setDesc("Folder where your daily logs are stored").addText(
      (text) => text.setPlaceholder("daily").setValue(this.plugin.settings.dailyNotesFolder).onChange(async (value) => {
        this.plugin.settings.dailyNotesFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Output Folder").setDesc("Folder where generated reports will be saved").addText(
      (text) => text.setPlaceholder("thinklog/output").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
        this.plugin.settings.outputFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Default Framework").setDesc("Default analysis framework for reports").addDropdown(
      (dropdown) => dropdown.addOption("mcksey", "McKinsey MECE").addOption("bcg", "BCG Matrix").addOption("palantir", "Palantir Hypothesis").setValue(this.plugin.settings.defaultFramework).onChange(async (value) => {
        this.plugin.settings.defaultFramework = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Show Streak").setDesc("Display day streak counter in the panel").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showStreak).onChange(async (value) => {
        this.plugin.settings.showStreak = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Language").setDesc("UI language").addDropdown(
      (dropdown) => dropdown.addOption("en", "English").addOption("ko", "\uD55C\uAD6D\uC5B4").setValue(this.plugin.settings.language).onChange(async (value) => {
        this.plugin.settings.language = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
var THINKLOG_STYLES = `
.thinklog-container {
  padding: 0;
  height: 100%;
}

.tl-panel {
  display: flex;
  flex-direction: column;
  height: 100%;
  background: var(--background-primary);
}

.tl-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 20px;
  border-bottom: 1px solid var(--background-modifier-border);
}

.tl-brand {
  display: flex;
  align-items: center;
  gap: 8px;
  font-weight: 600;
  font-size: 14px;
}

.tl-logo {
  width: 20px;
  height: 20px;
  color: var(--interactive-accent);
}

.tl-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 8px 16px;
  border-radius: 6px;
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  border: none;
  transition: all 0.15s ease;
}

.tl-btn-icon {
  width: 32px;
  height: 32px;
  padding: 0;
  background: var(--background-secondary);
  color: var(--text-muted);
}

.tl-btn-icon:hover {
  background: var(--background-modifier-hover);
  color: var(--text-normal);
}

.tl-btn-icon svg {
  width: 16px;
  height: 16px;
}

.tl-btn-primary {
  background: var(--interactive-accent);
  color: white;
  width: 100%;
}

.tl-btn-primary:hover {
  background: var(--interactive-accent-hover);
}

.tl-btn-primary svg {
  width: 14px;
  height: 14px;
}

.tl-date-section {
  padding: 16px 20px;
  display: flex;
  align-items: center;
  gap: 12px;
}

.tl-date-badge {
  background: var(--text-normal);
  color: var(--background-primary);
  padding: 4px 10px;
  border-radius: 4px;
  font-size: 12px;
  font-weight: 600;
}

.tl-date-relative {
  font-size: 13px;
  color: var(--text-muted);
}

.tl-streak-card {
  margin: 0 20px 16px;
  padding: 16px;
  background: linear-gradient(135deg, var(--interactive-accent) 0%, #4f46e5 100%);
  border-radius: 10px;
  text-align: center;
  color: white;
}

.tl-streak-number {
  font-size: 28px;
  font-weight: 700;
}

.tl-streak-label {
  font-size: 12px;
  opacity: 0.9;
}

.tl-section {
  padding: 0 20px 20px;
}

.tl-section-label {
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  color: var(--text-muted);
  margin-bottom: 12px;
}

.tl-theme-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.tl-theme-option {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 10px 12px;
  background: var(--background-secondary);
  border-radius: 8px;
  cursor: pointer;
  border: 2px solid transparent;
  transition: all 0.15s ease;
}

.tl-theme-option:hover {
  border-color: var(--background-modifier-border);
}

.tl-theme-option.active {
  border-color: var(--interactive-accent);
  background: var(--background-primary-alt);
}

.tl-theme-icon {
  width: 32px;
  height: 32px;
  border-radius: 6px;
  background: var(--background-primary);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 14px;
}

.tl-theme-info {
  flex: 1;
  min-width: 0;
}

.tl-theme-name {
  font-size: 13px;
  font-weight: 500;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.tl-theme-meta {
  font-size: 11px;
  color: var(--text-muted);
}

.tl-new-theme-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 10px;
  border: 2px dashed var(--background-modifier-border);
  border-radius: 8px;
  background: transparent;
  color: var(--text-muted);
  font-size: 13px;
  cursor: pointer;
  transition: all 0.15s ease;
}

.tl-new-theme-btn:hover {
  border-color: var(--interactive-accent);
  color: var(--interactive-accent);
}

.tl-new-theme-btn svg {
  width: 14px;
  height: 14px;
}

.tl-action-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 8px;
}

.tl-action-btn {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  padding: 14px 10px;
  background: var(--background-secondary);
  border: 1px solid var(--background-modifier-border);
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.15s ease;
  font-size: 12px;
  color: var(--text-muted);
}

.tl-action-btn:hover {
  border-color: var(--interactive-accent);
  color: var(--interactive-accent);
  background: var(--background-primary-alt);
}

.tl-action-icon {
  font-size: 18px;
}

.tl-stats-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 12px;
}

.tl-stat {
  text-align: center;
  padding: 12px;
  background: var(--background-secondary);
  border-radius: 8px;
}

.tl-stat-value {
  font-size: 20px;
  font-weight: 700;
  color: var(--text-normal);
}

.tl-stat-label {
  font-size: 10px;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.3px;
}

.tl-footer {
  margin-top: auto;
  padding: 16px 20px;
  border-top: 1px solid var(--background-modifier-border);
}
`;
